name: DataSync
version: "0.8.0-SNAPSHOT"
main: org.anvilpowered.datasync.nukkit.DataSyncNukkit
api: ["1.0.0"]
author : AnvilPowered
description: A plugin to synchronize player inventories with a database
website: https://www.anvilpowered.org
depend: [Anvil]
commands:
  datasync:
    description: DataSync root command
    aliases:
      - sync
