name: DataSync
version: "0.3.0-SNAPSHOT"
main: org.anvilpowered.datasync.spigot.DataSyncSpigot
api-version: 1.15
authors: [Cableguy20, STG_Allen]
description: A plugin to synchronize player inventories with a database
depend: [Anvil]
commands:
  datasync:
    description: DataSync root command
    aliases:
      - sync
